app_coder/urls.py
from django.urls import path
from app_coder import views


app_name='app_coder'
urlpatterns = [
    # Django documentation -->  https://docs.djangoproject.com/en/4.0/topics/class-based-views/generic-editing/
    # Confirmo la url de la documentación es correcta, deben hacer scroll hasta esta parte:
    #
    # from django.urls import path
    # from myapp.views import AuthorCreateView, AuthorDeleteView, AuthorUpdateView
    # urlpatterns = [
    #     # ...
    #     path('author/add/', AuthorCreateView.as_view(), name='author-add'),
    #     path('author/<int:pk>/', AuthorUpdateView.as_view(), name='author-update'),
    #     path('author/<int:pk>/delete/', AuthorDeleteView.as_view(), name='author-delete'),
    # ]
    #
    # Acá se ve la forma clara cómo Django realiza de forma stándar los nombres para urls, views y name del path.
    path('', views.index, name="Index"),
    path('products', views.ProductListView.as_view(), name='product-list'),
    path('product/add/', views.ProductCreateView.as_view(), name='product-add'),
    path('product/<int:pk>/detail', views.ProductDetailView.as_view(), name='product-detail'),
    path('product/<int:pk>/update', views.ProductUpdateView.as_view(), name='product-update'),
    path('product/<int:pk>/delete', views.ProductDeleteView.as_view(), name='product-delete'),
    path('clients', views.ClientListView.as_view(), name='client-list'),
    path('client/add/', views.ClientCreateView.as_view(), name='client-add'),
    path('client/<int:pk>/detail', views.ClientDetailView.as_view(), name='client-detail'),
    path('client/<int:pk>/update', views.ClientUpdateView.as_view(), name='client-update'),
    path('client/<int:pk>/delete', views.ClientDeleteView.as_view(), name='client-delete'),
    path('questions', views.questionform, name="question-form"),
    path('search', views.search, name='Search'),
]

coderhouse_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_coder.urls')),
]

app_coder/models.py
from django.db import models


class Product(models.Model):
    nameprod = models.CharField(max_length=40)
    price = models.CharField(max_length=10)

    def __str__(self):
        return f"Producto: {self.nameprod} - Precio ${self.price}"


class Client(models.Model):
    name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    email = models.EmailField()

    def __str__(self):
        return f"Cliente Apellido y Nombre: {self.name} {self.last_name} -- e-mail: {self.email}"


class Question(models.Model):
    name = models.CharField(max_length=40)
    phone = models.CharField(max_length=40)
    email = models.EmailField()
    question = models.CharField(max_length=150)

    def __str__(self):
        return f"Consulta: {self.question} - Datos de contacto: {self.name} - {self.phone} - {self.email}"

app_coder/forms.py
from django import forms

class QuestionForm(forms.Form):
    name = forms.CharField(max_length=40, label='Nombre')
    question = forms.CharField(max_length=150, label='Pregunta')
    phone = forms.CharField(max_length=40, label='Telefono')
    email = forms.EmailField(label='Email')

class ProductForm(forms.Form):
    nameprod = forms.CharField(max_length=40, min_length=3, label='Nombre')
    price = forms.CharField(max_length=10, label='Precio')

class ClientForm(forms.Form):
    name = forms.CharField(max_length=40, label='Nombre')
    last_name = forms.CharField(max_length=40, label='Apellido')
    email = forms.EmailField(label='Email')

app_coder/views.py
from django.shortcuts import  render
from django.http import HttpResponse
from django.views.generic import edit
from app_coder.forms import ProductForm, ClientForm, QuestionForm
from app_coder.models import Product, Client, Question
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.db.models import Q
from django.forms.models import model_to_dict

###################### Home ###################### 

def index(request):
    return render(request, "app_coder/index.html")

###################### Product ###################### 

class ProductListView(ListView):
    model = Product
    template_name= "app_coder/product_list.html"

class ProductDetailView(DetailView):
    model = Product
    template_name= "app_coder/product_detail.html"

class ProductCreateView(CreateView):
    model = Product
    success_url = reverse_lazy('app_coder:product-list')
    fields = ["nameprod", "price"]

class ProductUpdateView(UpdateView):
    model = Product
    success_url = reverse_lazy('app_coder:product-list')
    fields = ["nameprod", "price"]

class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('app_coder:product-list')

###################### Clients ###################### 

class ClientListView(ListView):
    model = Client
    template_name= "app_coder/client_list.html"

class ClientDetailView(DetailView):
    model = Client
    template_name= "app_coder/client_detail.html"    

class ClientCreateView(CreateView):
    model = Client
    success_url = reverse_lazy('app_coder:client-list')
    fields = ["name", "last_name", "email"]

class ClientUpdateView(UpdateView):
    model = Client
    success_url = reverse_lazy('app_coder:client-list')
    fields = ["name", "last_name", "email"]

class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy('app_coder:client-list')

###################### Question ###################### 

def questionform(request):
    if request.method == 'POST':
        questions_form = QuestionForm(request.POST)
        print(questions_form)
        if  questions_form.is_valid:
            information = questions_form.cleaned_data
            questions = questions(name=information['nombre'], consulta=information['consulta'], phone=information['telefono'], email=information['email'])
            questions.save()
            return render(request, 'app_coder/index.html')
    else:
        questions_form= QuestionForm()
    return render(request, 'app_coder/question_form.html', {'questions_form': questions_form})

###################### Search ###################### 

def search(request):
    context_dict = dict() # evita que se rompa el search cuando se hace una busqueda vacia
    if request.GET['product_text_search']:
        print(request.__dict__)
        search_param = request.GET['product_text_search']
        products = Product.objects.filter(nameprod__contains=search_param)
        context_dict = {
            'products': products
        }
    elif request.GET['product_price_search']:
        search_param = request.GET['product_price_search']
        products = Product.objects.filter(price__contains=search_param)
        context_dict = {
            'products': products
        }
    elif request.GET['product_all_search']:
        search_param = request.GET['product_all_search']
        query = Q(nameprod__contains=search_param)
        query.add(Q(price__contains=search_param), Q.OR)
        products = Product.objects.filter(query)
        context_dict = {
            'products': products
        }
    elif request.GET['client_text_search']:
        search_param = request.GET['client_text_search']
        clients = Client.objects.filter(name__contains=search_param)
        context_dict = {
            'clients': clients
        }
    elif request.GET['client_last_name_search']:
        search_param = request.GET['client_last_name_search']
        clients = Client.objects.filter(last_name__contains=search_param)
        context_dict = {
            'clients': clients
        }
    elif request.GET['client_email_search']:
        search_param = request.GET['client_email_search']
        clients = Client.objects.filter(email__contains=search_param)
        context_dict = {
            'clients': clients
        }
    elif request.GET['client_all_search']:
        search_param = request.GET['client_all_search']
        query = Q(name__contains=search_param)
        query.add(Q(last_name__contains=search_param), Q.OR)
        query.add(Q(email__contains=search_param), Q.OR)
        clients = Client.objects.filter(query)
        context_dict = {
            'clients': clients
        }    
    return render(
        request=request,
        context=context_dict,
        template_name="app_coder/index.html",
    )

app_coder/templates/app_coder/base.html
<!DOCTYPE html>
<html lang="en">
    <head>

        {% load static %}

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Coder3DPrint</title>
        <link rel="icon" type="image/x-icon" href="{% static 'app_coder/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'app_coder/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
            <div class="container px-5">
                <a class="navbar-brand" href="#page-top">Coder3DPrint</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'app_coder:Index' %}">Inicio</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'app_coder:product-list' %}">Productos</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'app_coder:client-list' %}">Clientes</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'app_coder:question-form' %}">Consultas</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        {% block content %}

        {% endblock %}

        <!-- Footer-->
        <footer class="py-5 bg-black">
            <div class="container px-5">
                <p class="m-0 text-center text-white small">Copyright &copy; Coderhouse 2022
                    <br><br>
                    <a href="https://github.com/ltiisidii"><i class="fab fa-github fa-2x"></i></a>

                    <p style="text-align: center;" class="nav-item">
                        <br>
                        <a class="nav-link" href="{% url 'app_coder:Index' %}">Inicio</a>
                        <a class="nav-link" href="{% url 'app_coder:product-list' %}">Productos</a>
                        <a class="nav-link" href="{% url 'app_coder:client-list' %}">Clientes</a>
                        <a class="nav-link" href="{% url 'app_coder:question-form' %}">Consultas</a>

                    </p>
                    
                </p>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'app_coder/js/scripts.js' %}"></script>
    </body>
</html>

app_coder/templates/app_coder/client_confirm_delete.html
{% extends "app_coder/base.html" %}

{% load static %}

{% block content %}

<!-- Header -->
<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container px-5">
            <h1 class="masthead-heading mb-0">Eliminar {{ object.nameprod }}</h1>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>

<!-- Content section 1-->
<section id="scroll">
            
    <div class="container px-5">
    <br><br>
        <div class="row gx-5 align-items-center">

            

            <form method="post"> {% csrf_token %}

                <br><br><br><br>
                <h3>¿Estas seguro que quiere borrar "{{ object }}"?</h3>

                <br><br>

                <input class="btn btn-primary" type="submit" value="Si, borrar" />



            </form>
                <br><br>
                </div>
                <br>
            </div>
        </section>         

{% endblock %}

app_coder/templates/app_coder/client_detail.html
{% extends "app_coder/base.html" %}

{% load static %}

{% block content %}

<!-- Header -->
<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container px-5">
            <h1 class="masthead-heading mb-0">Detalles de {{ client.nameprod }}</h1>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>

<!-- Content section 1-->
<section id="scroll">
    <div class="container px-5">
    <br><br>
        <div class="row gx-5 align-items-center">
            <br><br><br><br><br><br>
            <h3> Detalles de clientes</h3>
                <p> Nombre: <i> {{ client.name }} </i></p>
                <p> Apellido: <i> {{ client.last_name }} </i></p>
                <p> Email: <i> {{ client.email }} </i></p>
                <p>
                    <a class="btn btn-primary" href="{% url 'app_coder:client-list' %}">Regresar</a>
                </p>
        </div>
        <br>
    </div>
</section>

{% endblock %}

app_coder/templates/app_coder/client_form.html
{% extends "app_coder/base.html" %}

{% load static %}

{% block content %}

<!-- Header -->
<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container px-5">
            <h1 class="masthead-heading mb-0">Formulario de clients</h1>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>

<!-- Content section 1-->
<section id="scroll">
            
    <div class="container px-5">
    <br><br>
        <div class="row gx-5 align-items-center">
            <br><br><br><br><br><br>
            <h3> Formulario de clientes </h3>
                
            <form method="POST"> {% csrf_token %}

                {{form.as_table}}
    
    
                <input class="btn btn-primary" type="submit" value="Enviar" />
    
            </form>
           

        </div>
        <br>
    </div>
</section>

{% endblock %}

app_coder/templates/app_coder/client_list.html
{% extends "app_coder/base.html" %}

{% load static %}

{% block content %}


<!-- Header -->
<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container px-5">
            <h1 class="masthead-heading mb-0">Lista de clientes</h1>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>

<!-- Content section 1-->
        <section id="scroll">
            <div class="container px-5">
                <h2>Lista de Clientes</h2>
            <a class="card_custom" href="{% url 'app_coder:client-add' %}">Crear nuevo Cliente</a>
            <hr>
            </hr>
            <br><br>
                <div class="row gx-5 align-items-center">
                        <ul>
                            {% for client in client_list %}
                                <li> 
                                    <p> {{ client.name }} {{ client.last_name }} </p>
                                    <p>
                                        <a href=" {% url 'app_coder:client-detail' client.id %} ">
                                            <i class="fa fa-eye" style="color: rgb(0, 0, 255);"> </i>
                                        </a>
                                        <a href=" {% url 'app_coder:client-update' client.id %} ">
                                            <i class="fa fa-pencil" style="color: rgb(0, 0, 190);"> </i>
                                        </a>
                                        <a href=" {% url 'app_coder:client-delete' client.id %} "> 
                                            <i class="fa fa-trash" style="color: rgb(0, 0, 100);"> </i>
                                        </a>
                                    </p>
                                </li>
                            {% endfor %}
                        </ul>
                        <p>
                            <a class="btn btn-primary" href="{% url 'app_coder:Index' %}">Regresar a inicio</a>
                        </p>
                </div>
                <br>
            </div>
        </section>

{% endblock %}

app_coder/templates/app_coder/index.html
{% extends "app_coder/base.html" %}

{% load static %}

{% block content %}

<!-- Header-->
<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container px-5">
            <h1 class="masthead-heading mb-0">Coder3DPrint</h1>
            <h2 class="masthead-subheading mb-0">Servicio de impresion 3D</h2>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>

<!-- Content section 1-->
<section id="scroll">
    
    <div class="container px-5">
    <br><br>
        <div class="row gx-5 align-items-center">
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                        <!-- Search Products-->
                        <h2>Buscador de Productos</h2>
                        <hr></hr>
                        
                        <form action="search" method="GET">
                            <div>
                                <input type="text" name="product_text_search" id="product_nameprod" placeholder="Busqueda por nombre">
                                <input type="submit" value="Buscar por Nombre">
                            </div>
                            <div>
                                <input type="number" name="product_price_search" id="product_price" placeholder="Busqueda por precio">
                                <input type="submit" value="Buscar por Precio">
                            </div>
                            <div>
                                <input type="text" name="product_all_search" id="product_code_or_name" placeholder="Busqueda general">
                                <input type="submit" value="Buscar">
                            </div>

                        <hr></hr>
                        {% if products %}
                            <ul>
                                {% for product in products %}
                                    <li>
                                        Nombre: {{product.nameprod}}
                                        -- Precio: {{product.price}}
                                    </li>
                                {% endfor %}
                            </ul>
                        {% endif %} 
                        
                        <!-- Search Products-->
                        <h2>Buscador de Clientes</h2>
                        <hr></hr>
                            <div>
                                <input type="text" name="client_text_search" id="client_name" placeholder="Busqueda por nombre">
                                <input type="submit" value="Buscar por Nombre">
                            </div>
                            <div>
                                <input type="text" name="client_last_name_search" id="client_last_name" placeholder="Busqueda por apellido">
                                <input type="submit" value="Buscar por Apellido">
                            </div>
                            <div>
                                <input type="text" name="client_email_search" id="client_email" placeholder="Busqueda por email">
                                <input type="submit" value="Buscar por Email">
                            </div>
                            <div>
                                <input type="text" name="client_all_search" id="client_name_or_last_name_or_email" placeholder="Busqueda general">
                                <input type="submit" value="Buscar">
                            </div>
                        
                        </form>
                        
                        <hr></hr>
                        
                        {% if clients %}
                            <ul>
                                {% for client in clients %}
                                    <li>
                                        Nombre: {{client.name}}
                                        -- Apellido: {{client.last_name}}
                                        -- Email: {{client.email}}
                                    </li>
                                {% endfor %}
                            </ul>
                        {% endif %}     
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

app_coder/templates/app_coder/product_confirm_delete.html
{% extends "app_coder/base.html" %}

{% load static %}

{% block content %}

<!-- Header -->
<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container px-5">
            <h1 class="masthead-heading mb-0">Eliminar {{ object.nameprod }}</h1>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>

<!-- Content section 1-->
<section id="scroll">
            
    <div class="container px-5">
    <br><br>
        <div class="row gx-5 align-items-center">

            

            <form method="post"> {% csrf_token %}

                <br><br><br><br>
                <h3>¿Estas seguro que quiere borrar "{{ object }}"?</h3>

                <br><br>

                <input class="btn btn-primary" type="submit" value="Si, borrar" />



            </form>
                <br><br>
                </div>
                <br>
            </div>
        </section>         

{% endblock %}

app_coder/templates/app_coder/product_detail.html
{% extends "app_coder/base.html" %}

{% load static %}

{% block content %}

<!-- Header -->
<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container px-5">
            <h1 class="masthead-heading mb-0">Detalles de {{ product.nameprod }}</h1>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>

<!-- Content section 1-->
<section id="scroll">
    <div class="container px-5">
    <br><br>
        <div class="row gx-5 align-items-center">
            <br><br><br><br><br><br>
            <h3> Detalles de productos</h3>
                <p> Nombre: <i> {{ product.nameprod }} </i></p>
                <p> Precio: $<i> {{ product.price }} </i></p>
                <p>
                    <a class="btn btn-primary" href="{% url 'app_coder:product-list' %}">Regresar</a>
                </p>
        </div>
        <br>
    </div>
</section>

{% endblock %}

app_coder/templates/app_coder/product_form.html
{% extends "app_coder/base.html" %}

{% load static %}

{% block content %}

<!-- Header -->
<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container px-5">
            <h1 class="masthead-heading mb-0">Formulario de productos</h1>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>

<!-- Content section 1-->
<section id="scroll">
            
    <div class="container px-5">
    <br><br>
        <div class="row gx-5 align-items-center">
            <br><br><br><br><br><br>
            <h3> Formulario de productos </h3>
                
            <form method="POST"> {% csrf_token %}

                {{form.as_table}}
    
    
                <input class="btn btn-primary" type="submit" value="Enviar" />
    
            </form>
           

        </div>
        <br>
    </div>
</section>

{% endblock %}

app_coder/templates/app_coder/product_list.html
{% extends "app_coder/base.html" %}

{% load static %}

{% block content %}


<!-- Header -->
<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container px-5">
            <h1 class="masthead-heading mb-0">Lista de productos</h1>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>

<!-- Content section 1-->
        <section id="scroll">
            <div class="container px-5">
                <h2>Lista de Productos</h2>
            <a class="card_custom" href="{% url 'app_coder:product-add' %}">Crear nuevo Producto</a>
            <hr>
            </hr>
            <br><br>
                <div class="row gx-5 align-items-center">
                        <ul>
                            {% for product in product_list %}
                                <li> 
                                    <p> {{ product.nameprod }} </p>
                                    <p>
                                        <a href=" {% url 'app_coder:product-detail' product.id %} ">
                                            <i class="fa fa-eye" style="color: rgb(0, 0, 255);"> </i>
                                        </a>
                                        <a href=" {% url 'app_coder:product-update' product.id %} ">
                                            <i class="fa fa-pencil" style="color: rgb(0, 0, 190);"> </i>
                                        </a>
                                        <a href=" {% url 'app_coder:product-delete' product.id %} "> 
                                            <i class="fa fa-trash" style="color: rgb(0, 0, 100);"> </i>
                                        </a>
                                    </p>
                                </li>
                            {% endfor %}
                        </ul>
                        <p>
                            <a class="btn btn-primary" href="{% url 'app_coder:Index' %}">Regresar a inicio</a>
                        </p>
                </div>
                <br>
            </div>
        </section>

{% endblock %}

app_coder/templates/app_coder/question_form.html
{% extends "app_coder/base.html" %}

{% load static %}

{% block content %}


<!-- Header -->
<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container px-5">
            <h1 class="masthead-heading mb-0">Consultas</h1>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>
    <br>
    <br>

    {% if questions_form.errors %}

    <p style="color: red;"> Datos erroneos.</p>

    {% endif %}

    <div class="container align-items-left">
        
        <h2>Dejanos tu consulta y te contestaremos a la brevedad.</h2>

        <form action="/AppCoder/consultasFormulario" method="POST">{% csrf_token%}
            
            <table style="color: #ee0979; font-weight: 300;">

                {{ questions_form.as_table }}


            </table>
            
            <br>

            <input type="submit" value="Enviar" class="btn btn-dark">
            <hr></hr>
            {% if question %}
                <ul>
                    {% for question in questions %}
                        <li>
                            Nombre: {{question.name}}
                            <br> Telefono: {{question.phone}}
                            <br> Email de contacto: {{question.email}}   
                            <br> Pregunta: {{question.question}}
                        </li>
                    {% endfor %}
                </ul>
            {% endif %} 
            <br><br>
        </form>
        
    </div>

{% endblock %}